### ISSUE TITLE
Unable to run test as written in package.json

### ISSUE THREAD

**Issue by mml1** [Slushnas/gather-phase-4#1]
I was unable to run your tests using npm test unless I changed the command a little bit. I recommend you change the following:

Current: 
```
"test": " sh bin\\mocha-test && sh bin\\wdio-test",
"test:mocha": " sh bin\\mocha-test || exit 0"
```

Changed: 
```
"test": " bin/mocha-test && bin/wdio-test",
"test:mocha": " bin//mocha-test || exit 0"
```

https://github.com/Slushnas/gather-phase-4/blob/master/package.json#L9-L10

**Comment by Slushnas** [comment]
Are you running the tests on Linux or Mac? I made some changes that allow me to run the tests on Windows using Git Bash and Linux (tested in Ubuntu). Hopefully this will work on Mac OS as well but I don't own a Mac to test it.
