### ISSUE TITLE
Alternative way of testing single item routes

### ISSUE THREAD

**Issue by mml1** [Slushnas/gather-phase-4#3]
An alternative option for testing the route for single item is:

```
describe('GET', () => {
    it('renders a single item ', async () => {
      const item = await seedItemToDatabase();
      const response = await request(app)
        .get(`/items/${item._id}`);
      
      assert.include(parseTextFromHTML(response.text, '#item-title'), item.title);
      assert.include(parseTextFromHTML(response.text, '#item-description'), item.description);
    });
  });
```

However, I like that you set up a test to test each item's presence individually. In terms of your method, the only suggestion I have is to see if you could set up:

```
  const item = await seedItemToDatabase();
      const response = await request(app)
        .get(`/items/${item._id}`);
```

once, the second underneath describe, before running the tests. 

https://github.com/Slushnas/gather-phase-4/blob/master/test/routes/single-item-test.js

**Comment by Slushnas** [comment]
I think I went a little overboard here by trying to follow the "only assert one thing" rule that I have been reading about. The asserts are really part of one concept: rendering the item with all three properties present. As such I have decided to condense the code like you mentioned.
